<?/** @var \Training\LayoutExample\Block\Layout\Index $block */?>
<h2><?= $block->getSubTitle()?></h2>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo quos molestiae dolore et, quaerat omnis fugiat culpa tenetur eos provident perferendis laudantium maxime. Modi qui sapiente iusto facilis voluptatem a.</p>

<?= $block->getChildHtml('layout_note')?>

<?= $block->getNodeHTML()?>

<?= $block->getChildHtml('cms_block_example')?>